### ISSUE TITLE
installation instructions do not inform folks how to operate on their "lappy"...

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/dsde-deep-learning#2]
a google search implies that keras can be installed via 

```
conda install -c conda-forge keras=2.0.2
```

is this a good substitute for the conda installation line in the wiki?

**Comment by lucidtronix** [comment]
Yes that should work! let's add a section for laptop environment setup

**Comment by yfarjoun** [comment]
hmm. but it isn't working for me. I'm getting an error reporting conflict when trying to install `opencv`

**Comment by lucidtronix** [comment]
Yeah opencv can be tricky.  You probably wont need it is just there because it is used for some visualization stuff.  I think what worked on my mac was first:

`conda install pillow`

then

`conda install -c https://conda.anaconda.org/menpo opencv3`

**Comment by yfarjoun** [comment]
That worked, in the sense that the commands didn't reach a conflict...but I am still unable to run the example:

```
(p2) $ python chrom_hmm_cnn.py
Using TensorFlow backend.
Arguments are Namespace(bed_file='/dsde/data/deep/wgEncodeAwgSegmentationCombinedGm12878.bed', inputs={'A': 0, 'C': 1, 'T': 2, 'G': 3}, labels={'WE': 3, 'E': 2, 'R': 6, 'PF': 1, 'T': 5, 'TSS': 0, 'CTCF': 4}, model='small', reference_fasta='/dsde/data/deep/Homo_sapiens_assembly19.fasta', samples=1000, window_size=128)
chrom_hmm_cnn.py:113: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(kernel_initializer="normal", activation="relu", input_shape=(128, 4), padding="valid", filters=40, kernel_size=16)`
  init='normal'))
Traceback (most recent call last):
  File "chrom_hmm_cnn.py", line 569, in <module>
    run() 
  File "chrom_hmm_cnn.py", line 43, in run
    make_small_model(args)
  File "chrom_hmm_cnn.py", line 67, in make_small_model
    model = build_small_chrom_label(args)
  File "chrom_hmm_cnn.py", line 113, in build_small_chrom_label
    init='normal'))
  File "/Users/yossiprivate/anaconda2/envs/p2/lib/python2.7/site-packages/keras/models.py", line 422, in add
    layer(x)
  File "/Users/yossiprivate/anaconda2/envs/p2/lib/python2.7/site-packages/keras/engine/topology.py", line 554, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/yossiprivate/anaconda2/envs/p2/lib/python2.7/site-packages/keras/layers/convolutional.py", line 156, in call
    dilation_rate=self.dilation_rate[0])
  File "/Users/yossiprivate/anaconda2/envs/p2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2816, in conv1d
    x = tf.nn.convolution(
AttributeError: 'module' object has no attribute 'convolution'
```

**Comment by yfarjoun** [comment]
oh. I see it's looking for a file on the Broad network....
